name: emenu
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  http: ^0.13.4
  provider: ^6.0.2
  sqflite: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
